### ISSUE TITLE
CentOS systemd recommendations

### ISSUE THREAD

**Issue by ShaneMcC** [ShaneMcC/docker-omsa#1]
Looking at https://hub.docker.com/_/centos we might want to include the following:

```
FROM centos:7
ENV container docker
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/sbin/init"]
```

And then they suggest a way of running things:
```
FROM local/c7-systemd
RUN yum -y install httpd; yum clean all; systemctl enable httpd.service
EXPOSE 80
CMD ["/usr/sbin/init"]
```

Need to check if this makes things better/worse/indifferent and include it if appropriate

**Comment by tigerblue77** [comment]
I think you can close this issue now CentOS is dead. Long live CentOS.

**Comment by tigerblue77** [comment]
I think you can close this issue now CentOS is dead. Long life CentOS.

**Comment by ShaneMcC** [comment]
This probably also still applies to alma, though from running the container for many years without this and no ill-effects that I have noticed, I suspect you're right and this can just be closed.

**Comment by tigerblue77** [comment]
Well, if this can reduce the image size, we can reopen it ! Even if I think that [switching to an Ubuntu image](https://github.com/ShaneMcC/docker-omsa/issues/6) would be the best
