### ISSUE TITLE
Newest version ?

### ISSUE THREAD

**Issue by tigerblue77** [ShaneMcC/docker-omsa#4]
Hello,
I tried your Docker image on my personal lab and it still works well ! Thanks for the job you've done here !

I was about to fork the project and try to upgrade it but I also found [this similar GitHub project](https://github.com/kamermans/docker-openmanage) on which you participated and I would like to know which one is "the best" ? They are both old but this one (ShaneMcC/docker-omsa) seems a lot easier to understand.

Thanks in advance !

**Comment by ShaneMcC** [comment]
I don't recall participating in that other project.

I think they do very similar things though that one hasn't been updated for a while.

Looking at their Dockerfile they're trying to avoid running much of systemd and provide a handy shell script for running the image.

I just opted to run systemd in the container (generally ill-advised) and it seemed to work and so I left it at that.

**Comment by tigerblue77** [comment]
Maybe we could merge all projects in one clean and up-to-date project ? :)
I can help

**Comment by ShaneMcC** [comment]
Hmm, I'm not getting any (noteworthy) systemd or modprobe errors in my logs.

There is an error from enabling the `rc.local.service` about it which is https://bugzilla.redhat.com/show_bug.cgi?id=1516188

That bug suggests we don't even need that line and that systemd will "do the right thing" automatically with a generator, so I'll remove that now to reduce the noise. (Possibly a left over from an older version of the image)

**Comment by ShaneMcC** [comment]
I've done some minor tidying/updating of the Dockerfile etc in:

commit 9ed60b7f91df23e70358da299bcd9f8f4d1ddb2e
commit 8c0e12d0bf01927df7447260d66b829de6e7e0c5
commit 4d9de662bdf05afd52e6085238061a1219a653c3

This also fixes an issue where `instsvcdrv.service` wasn't starting within the container.

This didn't seem to impact anything, but I'd prefer everything ran correctly.

**Comment by ShaneMcC** [comment]
I've also now upgraded to almalinux 9.1 in bfcab0daeed698f281ffa3133e953552d9359b04 and I believe this is now correctly installing the latest omsa version
